# Generated by carnix 0.10.0: carnix generate-nix --src .
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO // rec {
# libnixstore-sys-0.1.0

    crates.libnixstore_sys."0.1.0" = deps: { features?(features_.libnixstore_sys."0.1.0" deps {}) }: buildRustCrate {
      crateName = "libnixstore-sys";
      version = "0.1.0";
      authors = [ "Andreas Rammhold <andreas@rammhold.de>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] /home/andi/dev/private/local-nix-cache/../libnixstore-sys;
      libPath = "src/lib.rs";
      libName = "libnixstore_sys";
      crateBin =
        [{  name = "query_path_info";  path = "src/bin.rs"; }];

      buildDependencies = mapFeatures features ([
        (cratesIO.crates."bindgen"."${deps."libnixstore_sys"."0.1.0"."bindgen"}" deps)
        (cratesIO.crates."pkg_config"."${deps."libnixstore_sys"."0.1.0"."pkg_config"}" deps)
      ]);
    };
    features_.libnixstore_sys."0.1.0" = deps: f: updateFeatures f (rec {
      bindgen."${deps.libnixstore_sys."0.1.0".bindgen}".default = true;
      libnixstore_sys."0.1.0".default = (f.libnixstore_sys."0.1.0".default or true);
      pkg_config."${deps.libnixstore_sys."0.1.0".pkg_config}".default = true;
    }) [
      (cratesIO.features_.bindgen."${deps."libnixstore_sys"."0.1.0"."bindgen"}" deps)
      (cratesIO.features_.pkg_config."${deps."libnixstore_sys"."0.1.0"."pkg_config"}" deps)
    ];


# end
# local-nix-cache-0.1.0

    crates.local_nix_cache."0.1.0" = deps: { features?(features_.local_nix_cache."0.1.0" deps {}) }: buildRustCrate {
      crateName = "local-nix-cache";
      version = "0.1.0";
      authors = [ "Andreas Rammhold <andreas@rammhold.de>" ];
      edition = "2018";
      src = exclude [ ".git" "target" ] ./.;
      dependencies = mapFeatures features ([
        (cratesIO.crates."actix_web"."${deps."local_nix_cache"."0.1.0"."actix_web"}" deps)
        (cratesIO.crates."clap"."${deps."local_nix_cache"."0.1.0"."clap"}" deps)
        (cratesIO.crates."env_logger"."${deps."local_nix_cache"."0.1.0"."env_logger"}" deps)
        (crates."libnixstore_sys"."${deps."local_nix_cache"."0.1.0"."libnixstore_sys"}" deps)
        (cratesIO.crates."reqwest"."${deps."local_nix_cache"."0.1.0"."reqwest"}" deps)
        (cratesIO.crates."rusqlite"."${deps."local_nix_cache"."0.1.0"."rusqlite"}" deps)
        (cratesIO.crates."tempdir"."${deps."local_nix_cache"."0.1.0"."tempdir"}" deps)
      ]);
    };
    features_.local_nix_cache."0.1.0" = deps: f: updateFeatures f (rec {
      actix_web."${deps.local_nix_cache."0.1.0".actix_web}".default = true;
      clap."${deps.local_nix_cache."0.1.0".clap}".default = true;
      env_logger."${deps.local_nix_cache."0.1.0".env_logger}".default = true;
      libnixstore_sys."${deps.local_nix_cache."0.1.0".libnixstore_sys}".default = true;
      local_nix_cache."0.1.0".default = (f.local_nix_cache."0.1.0".default or true);
      reqwest."${deps.local_nix_cache."0.1.0".reqwest}".default = true;
      rusqlite = fold recursiveUpdate {} [
        { "${deps.local_nix_cache."0.1.0".rusqlite}"."trace" = true; }
        { "${deps.local_nix_cache."0.1.0".rusqlite}".default = true; }
      ];
      tempdir."${deps.local_nix_cache."0.1.0".tempdir}".default = true;
    }) [
      (cratesIO.features_.actix_web."${deps."local_nix_cache"."0.1.0"."actix_web"}" deps)
      (cratesIO.features_.clap."${deps."local_nix_cache"."0.1.0"."clap"}" deps)
      (cratesIO.features_.env_logger."${deps."local_nix_cache"."0.1.0"."env_logger"}" deps)
      (features_.libnixstore_sys."${deps."local_nix_cache"."0.1.0"."libnixstore_sys"}" deps)
      (cratesIO.features_.reqwest."${deps."local_nix_cache"."0.1.0"."reqwest"}" deps)
      (cratesIO.features_.rusqlite."${deps."local_nix_cache"."0.1.0"."rusqlite"}" deps)
      (cratesIO.features_.tempdir."${deps."local_nix_cache"."0.1.0"."tempdir"}" deps)
    ];


# end

  };

  local_nix_cache = crates.crates.local_nix_cache."0.1.0" deps;
  __all = [ (local_nix_cache {}) ];
  deps.actix."0.7.9" = {
    actix_derive = "0.3.2";
    bitflags = "1.0.5";
    bytes = "0.4.12";
    crossbeam_channel = "0.3.8";
    failure = "0.1.5";
    fnv = "1.0.6";
    futures = "0.1.26";
    log = "0.4.6";
    parking_lot = "0.7.1";
    smallvec = "0.6.9";
    tokio = "0.1.19";
    tokio_codec = "0.1.1";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    tokio_signal = "0.2.7";
    tokio_tcp = "0.1.3";
    tokio_timer = "0.2.10";
    trust_dns_proto = "0.5.0";
    trust_dns_resolver = "0.10.3";
    uuid = "0.7.4";
    libc = "0.2.54";
  };
  deps.actix_net."0.2.6" = {
    actix = "0.7.9";
    bytes = "0.4.12";
    futures = "0.1.26";
    log = "0.4.6";
    mio = "0.6.16";
    net2 = "0.2.33";
    num_cpus = "1.10.0";
    slab = "0.4.2";
    tokio = "0.1.19";
    tokio_codec = "0.1.1";
    tokio_current_thread = "0.1.6";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    tokio_tcp = "0.1.3";
    tokio_timer = "0.2.10";
    tower_service = "0.1.0";
    trust_dns_resolver = "0.10.3";
  };
  deps.actix_web."0.7.19" = {
    actix = "0.7.9";
    actix_net = "0.2.6";
    base64 = "0.10.1";
    bitflags = "1.0.5";
    brotli2 = "0.3.2";
    byteorder = "1.3.1";
    bytes = "0.4.12";
    cookie = "0.11.1";
    encoding = "0.2.33";
    failure = "0.1.5";
    flate2 = "1.0.7";
    futures = "0.1.26";
    futures_cpupool = "0.1.8";
    h2 = "0.1.18";
    http = "0.1.17";
    httparse = "1.3.3";
    language_tags = "0.2.2";
    lazy_static = "1.3.0";
    lazycell = "1.2.1";
    log = "0.4.6";
    mime = "0.3.13";
    mime_guess = "2.0.0-alpha.6";
    mio = "0.6.16";
    net2 = "0.2.33";
    num_cpus = "1.10.0";
    parking_lot = "0.7.1";
    percent_encoding = "1.0.1";
    rand = "0.6.5";
    regex = "1.1.6";
    serde = "1.0.90";
    serde_json = "1.0.39";
    serde_urlencoded = "0.5.5";
    sha1 = "0.6.0";
    slab = "0.4.2";
    smallvec = "0.6.9";
    time = "0.1.42";
    tokio = "0.1.19";
    tokio_current_thread = "0.1.6";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    tokio_tcp = "0.1.3";
    tokio_timer = "0.2.10";
    url = "1.7.2";
    v_htmlescape = "0.4.3";
    version_check = "0.1.5";
  };
  deps.actix_derive."0.3.2" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
  };
  deps.adler32."1.0.3" = {};
  deps.aho_corasick."0.7.3" = {
    memchr = "2.2.0";
  };
  deps.ansi_term."0.11.0" = {
    winapi = "0.3.7";
  };
  deps.arc_swap."0.3.11" = {};
  deps.arrayvec."0.4.10" = {
    nodrop = "0.1.13";
  };
  deps.atty."0.2.11" = {
    termion = "1.5.2";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.autocfg."0.1.2" = {};
  deps.backtrace."0.3.15" = {
    cfg_if = "0.1.7";
    rustc_demangle = "0.1.14";
    autocfg = "0.1.2";
    backtrace_sys = "0.1.28";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.backtrace_sys."0.1.28" = {
    libc = "0.2.54";
    cc = "1.0.36";
  };
  deps.base64."0.9.3" = {
    byteorder = "1.3.1";
    safemem = "0.3.0";
  };
  deps.base64."0.10.1" = {
    byteorder = "1.3.1";
  };
  deps.bindgen."0.42.3" = {
    bitflags = "1.0.5";
    cexpr = "0.3.5";
    cfg_if = "0.1.7";
    clang_sys = "0.26.4";
    clap = "2.33.0";
    env_logger = "0.5.13";
    lazy_static = "1.3.0";
    log = "0.4.6";
    peeking_take_while = "0.1.2";
    proc_macro2 = "0.3.5";
    quote = "0.5.2";
    regex = "1.1.6";
    which = "1.0.5";
  };
  deps.bitflags."1.0.5" = {};
  deps.brotli_sys."0.3.2" = {
    libc = "0.2.54";
    cc = "1.0.36";
  };
  deps.brotli2."0.3.2" = {
    brotli_sys = "0.3.2";
    libc = "0.2.54";
  };
  deps.build_const."0.2.1" = {};
  deps.byteorder."1.3.1" = {};
  deps.bytes."0.4.12" = {
    byteorder = "1.3.1";
    iovec = "0.1.2";
  };
  deps.cc."1.0.36" = {};
  deps.cexpr."0.3.5" = {
    nom = "4.2.3";
  };
  deps.cfg_if."0.1.7" = {};
  deps.clang_sys."0.26.4" = {
    glob = "0.2.11";
    libc = "0.2.54";
    libloading = "0.5.0";
  };
  deps.clap."2.33.0" = {
    atty = "0.2.11";
    bitflags = "1.0.5";
    strsim = "0.8.0";
    textwrap = "0.11.0";
    unicode_width = "0.1.5";
    vec_map = "0.8.1";
    ansi_term = "0.11.0";
  };
  deps.cloudabi."0.0.3" = {
    bitflags = "1.0.5";
  };
  deps.cookie."0.11.1" = {
    base64 = "0.9.3";
    ring = "0.13.5";
    time = "0.1.42";
    url = "1.7.2";
  };
  deps.cookie_store."0.5.1" = {
    cookie = "0.11.1";
    failure = "0.1.5";
    failure_derive = "0.1.5";
    idna = "0.1.5";
    log = "0.4.6";
    publicsuffix = "1.5.2";
    serde = "1.0.90";
    serde_derive = "1.0.90";
    serde_json = "1.0.39";
    time = "0.1.42";
    try_from = "0.3.2";
    url = "1.7.2";
  };
  deps.core_foundation."0.6.4" = {
    core_foundation_sys = "0.6.2";
    libc = "0.2.54";
  };
  deps.core_foundation_sys."0.6.2" = {};
  deps.crc."1.8.1" = {
    build_const = "0.2.1";
  };
  deps.crc32fast."1.2.0" = {
    cfg_if = "0.1.7";
  };
  deps.crossbeam_channel."0.3.8" = {
    crossbeam_utils = "0.6.5";
    smallvec = "0.6.9";
  };
  deps.crossbeam_deque."0.7.1" = {
    crossbeam_epoch = "0.7.1";
    crossbeam_utils = "0.6.5";
  };
  deps.crossbeam_epoch."0.7.1" = {
    arrayvec = "0.4.10";
    cfg_if = "0.1.7";
    crossbeam_utils = "0.6.5";
    lazy_static = "1.3.0";
    memoffset = "0.2.1";
    scopeguard = "0.3.3";
  };
  deps.crossbeam_queue."0.1.2" = {
    crossbeam_utils = "0.6.5";
  };
  deps.crossbeam_utils."0.6.5" = {
    cfg_if = "0.1.7";
    lazy_static = "1.3.0";
  };
  deps.dtoa."0.4.4" = {};
  deps.encoding."0.2.33" = {
    encoding_index_japanese = "1.20141219.5";
    encoding_index_korean = "1.20141219.5";
    encoding_index_simpchinese = "1.20141219.5";
    encoding_index_singlebyte = "1.20141219.5";
    encoding_index_tradchinese = "1.20141219.5";
  };
  deps.encoding_index_japanese."1.20141219.5" = {
    encoding_index_tests = "0.1.4";
  };
  deps.encoding_index_korean."1.20141219.5" = {
    encoding_index_tests = "0.1.4";
  };
  deps.encoding_index_simpchinese."1.20141219.5" = {
    encoding_index_tests = "0.1.4";
  };
  deps.encoding_index_singlebyte."1.20141219.5" = {
    encoding_index_tests = "0.1.4";
  };
  deps.encoding_index_tradchinese."1.20141219.5" = {
    encoding_index_tests = "0.1.4";
  };
  deps.encoding_index_tests."0.1.4" = {};
  deps.encoding_rs."0.8.17" = {
    cfg_if = "0.1.7";
  };
  deps.env_logger."0.5.13" = {
    atty = "0.2.11";
    humantime = "1.2.0";
    log = "0.4.6";
    regex = "1.1.6";
    termcolor = "1.0.4";
  };
  deps.env_logger."0.6.1" = {
    atty = "0.2.11";
    humantime = "1.2.0";
    log = "0.4.6";
    regex = "1.1.6";
    termcolor = "1.0.4";
  };
  deps.error_chain."0.8.1" = {
    backtrace = "0.3.15";
  };
  deps.error_chain."0.12.0" = {
    backtrace = "0.3.15";
  };
  deps.failure."0.1.5" = {
    backtrace = "0.3.15";
    failure_derive = "0.1.5";
  };
  deps.failure_derive."0.1.5" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
    synstructure = "0.10.1";
  };
  deps.fallible_iterator."0.1.6" = {};
  deps.fallible_streaming_iterator."0.1.9" = {};
  deps.flate2."1.0.7" = {
    crc32fast = "1.2.0";
    libc = "0.2.54";
    miniz_sys = "0.1.11";
    miniz_oxide_c_api = "0.2.1";
  };
  deps.fnv."1.0.6" = {};
  deps.foreign_types."0.3.2" = {
    foreign_types_shared = "0.1.1";
  };
  deps.foreign_types_shared."0.1.1" = {};
  deps.fuchsia_cprng."0.1.1" = {};
  deps.fuchsia_zircon."0.3.3" = {
    bitflags = "1.0.5";
    fuchsia_zircon_sys = "0.3.3";
  };
  deps.fuchsia_zircon_sys."0.3.3" = {};
  deps.futures."0.1.26" = {};
  deps.futures_cpupool."0.1.8" = {
    futures = "0.1.26";
    num_cpus = "1.10.0";
  };
  deps.glob."0.2.11" = {};
  deps.h2."0.1.18" = {
    byteorder = "1.3.1";
    bytes = "0.4.12";
    fnv = "1.0.6";
    futures = "0.1.26";
    http = "0.1.17";
    indexmap = "1.0.2";
    log = "0.4.6";
    slab = "0.4.2";
    string = "0.1.3";
    tokio_io = "0.1.12";
  };
  deps.hostname."0.1.5" = {
    libc = "0.2.54";
    winutil = "0.1.1";
  };
  deps.http."0.1.17" = {
    bytes = "0.4.12";
    fnv = "1.0.6";
    itoa = "0.4.4";
  };
  deps.httparse."1.3.3" = {};
  deps.humantime."1.2.0" = {
    quick_error = "1.2.2";
  };
  deps.hyper."0.12.28" = {
    bytes = "0.4.12";
    futures = "0.1.26";
    futures_cpupool = "0.1.8";
    h2 = "0.1.18";
    http = "0.1.17";
    httparse = "1.3.3";
    iovec = "0.1.2";
    itoa = "0.4.4";
    log = "0.4.6";
    net2 = "0.2.33";
    time = "0.1.42";
    tokio = "0.1.19";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    tokio_tcp = "0.1.3";
    tokio_threadpool = "0.1.14";
    tokio_timer = "0.2.10";
    want = "0.0.6";
    rustc_version = "0.2.3";
  };
  deps.hyper_tls."0.3.2" = {
    bytes = "0.4.12";
    futures = "0.1.26";
    hyper = "0.12.28";
    native_tls = "0.2.3";
    tokio_io = "0.1.12";
  };
  deps.idna."0.1.5" = {
    matches = "0.1.8";
    unicode_bidi = "0.3.4";
    unicode_normalization = "0.1.8";
  };
  deps.indexmap."1.0.2" = {};
  deps.iovec."0.1.2" = {
    libc = "0.2.54";
    winapi = "0.2.8";
  };
  deps.ipconfig."0.1.9" = {
    error_chain = "0.8.1";
    socket2 = "0.3.8";
    widestring = "0.2.2";
    winapi = "0.3.7";
    winreg = "0.5.1";
  };
  deps.itoa."0.4.4" = {};
  deps.kernel32_sys."0.2.2" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
  deps.language_tags."0.2.2" = {};
  deps.lazy_static."1.3.0" = {};
  deps.lazycell."1.2.1" = {};
  deps.libc."0.2.54" = {};
  deps.libloading."0.5.0" = {
    cc = "1.0.36";
    winapi = "0.3.7";
  };
  deps.libnixstore_sys."0.1.0" = {
    bindgen = "0.42.3";
    pkg_config = "0.3.14";
  };
  deps.libsqlite3_sys."0.13.0" = {
    pkg_config = "0.3.14";
  };
  deps.linked_hash_map."0.5.2" = {};
  deps.local_nix_cache."0.1.0" = {
    actix_web = "0.7.19";
    clap = "2.33.0";
    env_logger = "0.6.1";
    libnixstore_sys = "0.1.0";
    reqwest = "0.9.16";
    rusqlite = "0.17.0";
    tempdir = "0.3.7";
  };
  deps.lock_api."0.1.5" = {
    owning_ref = "0.4.0";
    scopeguard = "0.3.3";
  };
  deps.log."0.4.6" = {
    cfg_if = "0.1.7";
  };
  deps.lru_cache."0.1.2" = {
    linked_hash_map = "0.5.2";
  };
  deps.matches."0.1.8" = {};
  deps.memchr."2.2.0" = {};
  deps.memoffset."0.2.1" = {};
  deps.mime."0.3.13" = {
    unicase = "2.4.0";
  };
  deps.mime_guess."2.0.0-alpha.6" = {
    mime = "0.3.13";
    phf = "0.7.24";
    unicase = "1.4.2";
    phf_codegen = "0.7.24";
  };
  deps.miniz_sys."0.1.11" = {
    libc = "0.2.54";
    cc = "1.0.36";
  };
  deps.miniz_oxide."0.2.1" = {
    adler32 = "1.0.3";
  };
  deps.miniz_oxide_c_api."0.2.1" = {
    crc = "1.8.1";
    libc = "0.2.54";
    miniz_oxide = "0.2.1";
    cc = "1.0.36";
  };
  deps.mio."0.6.16" = {
    iovec = "0.1.2";
    lazycell = "1.2.1";
    log = "0.4.6";
    net2 = "0.2.33";
    slab = "0.4.2";
    fuchsia_zircon = "0.3.3";
    fuchsia_zircon_sys = "0.3.3";
    libc = "0.2.54";
    kernel32_sys = "0.2.2";
    miow = "0.2.1";
    winapi = "0.2.8";
  };
  deps.mio_uds."0.6.7" = {
    iovec = "0.1.2";
    libc = "0.2.54";
    mio = "0.6.16";
  };
  deps.miow."0.2.1" = {
    kernel32_sys = "0.2.2";
    net2 = "0.2.33";
    winapi = "0.2.8";
    ws2_32_sys = "0.2.1";
  };
  deps.native_tls."0.2.3" = {
    lazy_static = "1.3.0";
    libc = "0.2.54";
    security_framework = "0.3.1";
    security_framework_sys = "0.3.1";
    tempfile = "3.0.7";
    log = "0.4.6";
    openssl = "0.10.21";
    openssl_probe = "0.1.2";
    openssl_sys = "0.9.45";
    schannel = "0.1.15";
  };
  deps.net2."0.2.33" = {
    cfg_if = "0.1.7";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.nodrop."0.1.13" = {};
  deps.nom."4.2.3" = {
    memchr = "2.2.0";
    version_check = "0.1.5";
  };
  deps.num_cpus."1.10.0" = {
    libc = "0.2.54";
  };
  deps.numtoa."0.1.0" = {};
  deps.openssl."0.10.21" = {
    bitflags = "1.0.5";
    cfg_if = "0.1.7";
    foreign_types = "0.3.2";
    lazy_static = "1.3.0";
    libc = "0.2.54";
    openssl_sys = "0.9.45";
  };
  deps.openssl_probe."0.1.2" = {};
  deps.openssl_sys."0.9.45" = {
    libc = "0.2.54";
    autocfg = "0.1.2";
    cc = "1.0.36";
    pkg_config = "0.3.14";
  };
  deps.owning_ref."0.4.0" = {
    stable_deref_trait = "1.1.1";
  };
  deps.parking_lot."0.7.1" = {
    lock_api = "0.1.5";
    parking_lot_core = "0.4.0";
  };
  deps.parking_lot_core."0.4.0" = {
    rand = "0.6.5";
    smallvec = "0.6.9";
    rustc_version = "0.2.3";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.peeking_take_while."0.1.2" = {};
  deps.percent_encoding."1.0.1" = {};
  deps.phf."0.7.24" = {
    phf_shared = "0.7.24";
  };
  deps.phf_codegen."0.7.24" = {
    phf_generator = "0.7.24";
    phf_shared = "0.7.24";
  };
  deps.phf_generator."0.7.24" = {
    phf_shared = "0.7.24";
    rand = "0.6.5";
  };
  deps.phf_shared."0.7.24" = {
    siphasher = "0.2.3";
    unicase = "1.4.2";
  };
  deps.pkg_config."0.3.14" = {};
  deps.proc_macro2."0.3.5" = {
    unicode_xid = "0.1.0";
  };
  deps.proc_macro2."0.4.29" = {
    unicode_xid = "0.1.0";
  };
  deps.publicsuffix."1.5.2" = {
    error_chain = "0.12.0";
    idna = "0.1.5";
    lazy_static = "1.3.0";
    regex = "1.1.6";
    url = "1.7.2";
  };
  deps.quick_error."1.2.2" = {};
  deps.quote."0.5.2" = {
    proc_macro2 = "0.3.5";
  };
  deps.quote."0.6.12" = {
    proc_macro2 = "0.4.29";
  };
  deps.rand."0.4.6" = {
    rand_core = "0.3.1";
    rdrand = "0.4.0";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand."0.5.6" = {
    rand_core = "0.3.1";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand."0.6.5" = {
    rand_chacha = "0.1.1";
    rand_core = "0.4.0";
    rand_hc = "0.1.0";
    rand_isaac = "0.1.1";
    rand_jitter = "0.1.4";
    rand_os = "0.1.3";
    rand_pcg = "0.1.2";
    rand_xorshift = "0.1.1";
    autocfg = "0.1.2";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand_chacha."0.1.1" = {
    rand_core = "0.3.1";
    autocfg = "0.1.2";
  };
  deps.rand_core."0.3.1" = {
    rand_core = "0.4.0";
  };
  deps.rand_core."0.4.0" = {};
  deps.rand_hc."0.1.0" = {
    rand_core = "0.3.1";
  };
  deps.rand_isaac."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rand_jitter."0.1.4" = {
    rand_core = "0.4.0";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand_os."0.1.3" = {
    rand_core = "0.4.0";
    rdrand = "0.4.0";
    cloudabi = "0.0.3";
    fuchsia_cprng = "0.1.1";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.rand_pcg."0.1.2" = {
    rand_core = "0.4.0";
    autocfg = "0.1.2";
  };
  deps.rand_xorshift."0.1.1" = {
    rand_core = "0.3.1";
  };
  deps.rdrand."0.4.0" = {
    rand_core = "0.3.1";
  };
  deps.redox_syscall."0.1.54" = {};
  deps.redox_termios."0.1.1" = {
    redox_syscall = "0.1.54";
  };
  deps.regex."1.1.6" = {
    aho_corasick = "0.7.3";
    memchr = "2.2.0";
    regex_syntax = "0.6.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.6.6" = {
    ucd_util = "0.1.3";
  };
  deps.remove_dir_all."0.5.1" = {
    winapi = "0.3.7";
  };
  deps.reqwest."0.9.16" = {
    base64 = "0.10.1";
    bytes = "0.4.12";
    cookie = "0.11.1";
    cookie_store = "0.5.1";
    encoding_rs = "0.8.17";
    flate2 = "1.0.7";
    futures = "0.1.26";
    http = "0.1.17";
    hyper = "0.12.28";
    hyper_tls = "0.3.2";
    log = "0.4.6";
    mime = "0.3.13";
    mime_guess = "2.0.0-alpha.6";
    native_tls = "0.2.3";
    serde = "1.0.90";
    serde_json = "1.0.39";
    serde_urlencoded = "0.5.5";
    time = "0.1.42";
    tokio = "0.1.19";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_threadpool = "0.1.14";
    tokio_timer = "0.2.10";
    url = "1.7.2";
    uuid = "0.7.4";
  };
  deps.resolv_conf."0.6.2" = {
    hostname = "0.1.5";
    quick_error = "1.2.2";
  };
  deps.ring."0.13.5" = {
    untrusted = "0.6.2";
    cc = "1.0.36";
    lazy_static = "1.3.0";
    libc = "0.2.54";
  };
  deps.rusqlite."0.17.0" = {
    bitflags = "1.0.5";
    fallible_iterator = "0.1.6";
    fallible_streaming_iterator = "0.1.9";
    libsqlite3_sys = "0.13.0";
    lru_cache = "0.1.2";
    memchr = "2.2.0";
    time = "0.1.42";
  };
  deps.rustc_demangle."0.1.14" = {};
  deps.rustc_version."0.2.3" = {
    semver = "0.9.0";
  };
  deps.ryu."0.2.8" = {};
  deps.safemem."0.3.0" = {};
  deps.schannel."0.1.15" = {
    lazy_static = "1.3.0";
    winapi = "0.3.7";
  };
  deps.scopeguard."0.3.3" = {};
  deps.security_framework."0.3.1" = {
    core_foundation = "0.6.4";
    core_foundation_sys = "0.6.2";
    libc = "0.2.54";
    security_framework_sys = "0.3.1";
  };
  deps.security_framework_sys."0.3.1" = {
    core_foundation_sys = "0.6.2";
  };
  deps.semver."0.9.0" = {
    semver_parser = "0.7.0";
  };
  deps.semver_parser."0.7.0" = {};
  deps.serde."1.0.90" = {};
  deps.serde_derive."1.0.90" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
  };
  deps.serde_json."1.0.39" = {
    itoa = "0.4.4";
    ryu = "0.2.8";
    serde = "1.0.90";
  };
  deps.serde_urlencoded."0.5.5" = {
    dtoa = "0.4.4";
    itoa = "0.4.4";
    serde = "1.0.90";
    url = "1.7.2";
  };
  deps.sha1."0.6.0" = {};
  deps.signal_hook."0.1.9" = {
    libc = "0.2.54";
    signal_hook_registry = "1.0.1";
  };
  deps.signal_hook_registry."1.0.1" = {
    arc_swap = "0.3.11";
    libc = "0.2.54";
  };
  deps.siphasher."0.2.3" = {};
  deps.slab."0.4.2" = {};
  deps.smallvec."0.6.9" = {};
  deps.socket2."0.3.8" = {
    cfg_if = "0.1.7";
    libc = "0.2.54";
    redox_syscall = "0.1.54";
    winapi = "0.3.7";
  };
  deps.stable_deref_trait."1.1.1" = {};
  deps.string."0.1.3" = {};
  deps.strsim."0.8.0" = {};
  deps.syn."0.15.33" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    unicode_xid = "0.1.0";
  };
  deps.synstructure."0.10.1" = {
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
    unicode_xid = "0.1.0";
  };
  deps.tempdir."0.3.7" = {
    rand = "0.4.6";
    remove_dir_all = "0.5.1";
  };
  deps.tempfile."3.0.7" = {
    cfg_if = "0.1.7";
    rand = "0.6.5";
    remove_dir_all = "0.5.1";
    redox_syscall = "0.1.54";
    libc = "0.2.54";
    winapi = "0.3.7";
  };
  deps.termcolor."1.0.4" = {
    wincolor = "1.0.1";
  };
  deps.termion."1.5.2" = {
    numtoa = "0.1.0";
    libc = "0.2.54";
    redox_syscall = "0.1.54";
    redox_termios = "0.1.1";
  };
  deps.textwrap."0.11.0" = {
    unicode_width = "0.1.5";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.time."0.1.42" = {
    libc = "0.2.54";
    redox_syscall = "0.1.54";
    winapi = "0.3.7";
  };
  deps.tokio."0.1.19" = {
    bytes = "0.4.12";
    futures = "0.1.26";
    mio = "0.6.16";
    num_cpus = "1.10.0";
    tokio_codec = "0.1.1";
    tokio_current_thread = "0.1.6";
    tokio_executor = "0.1.7";
    tokio_fs = "0.1.6";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    tokio_sync = "0.1.5";
    tokio_tcp = "0.1.3";
    tokio_threadpool = "0.1.14";
    tokio_timer = "0.2.10";
    tokio_trace_core = "0.1.0";
    tokio_udp = "0.1.3";
    tokio_uds = "0.2.5";
  };
  deps.tokio_codec."0.1.1" = {
    bytes = "0.4.12";
    futures = "0.1.26";
    tokio_io = "0.1.12";
  };
  deps.tokio_current_thread."0.1.6" = {
    futures = "0.1.26";
    tokio_executor = "0.1.7";
  };
  deps.tokio_executor."0.1.7" = {
    crossbeam_utils = "0.6.5";
    futures = "0.1.26";
  };
  deps.tokio_fs."0.1.6" = {
    futures = "0.1.26";
    tokio_io = "0.1.12";
    tokio_threadpool = "0.1.14";
  };
  deps.tokio_io."0.1.12" = {
    bytes = "0.4.12";
    futures = "0.1.26";
    log = "0.4.6";
  };
  deps.tokio_reactor."0.1.9" = {
    crossbeam_utils = "0.6.5";
    futures = "0.1.26";
    lazy_static = "1.3.0";
    log = "0.4.6";
    mio = "0.6.16";
    num_cpus = "1.10.0";
    parking_lot = "0.7.1";
    slab = "0.4.2";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_sync = "0.1.5";
  };
  deps.tokio_signal."0.2.7" = {
    futures = "0.1.26";
    mio = "0.6.16";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    libc = "0.2.54";
    mio_uds = "0.6.7";
    signal_hook = "0.1.9";
    winapi = "0.3.7";
  };
  deps.tokio_sync."0.1.5" = {
    fnv = "1.0.6";
    futures = "0.1.26";
  };
  deps.tokio_tcp."0.1.3" = {
    bytes = "0.4.12";
    futures = "0.1.26";
    iovec = "0.1.2";
    mio = "0.6.16";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
  };
  deps.tokio_threadpool."0.1.14" = {
    crossbeam_deque = "0.7.1";
    crossbeam_queue = "0.1.2";
    crossbeam_utils = "0.6.5";
    futures = "0.1.26";
    log = "0.4.6";
    num_cpus = "1.10.0";
    rand = "0.6.5";
    slab = "0.4.2";
    tokio_executor = "0.1.7";
  };
  deps.tokio_timer."0.2.10" = {
    crossbeam_utils = "0.6.5";
    futures = "0.1.26";
    slab = "0.4.2";
    tokio_executor = "0.1.7";
  };
  deps.tokio_trace_core."0.1.0" = {
    lazy_static = "1.3.0";
  };
  deps.tokio_udp."0.1.3" = {
    bytes = "0.4.12";
    futures = "0.1.26";
    log = "0.4.6";
    mio = "0.6.16";
    tokio_codec = "0.1.1";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
  };
  deps.tokio_uds."0.2.5" = {
    bytes = "0.4.12";
    futures = "0.1.26";
    iovec = "0.1.2";
    libc = "0.2.54";
    log = "0.4.6";
    mio = "0.6.16";
    mio_uds = "0.6.7";
    tokio_codec = "0.1.1";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
  };
  deps.tower_service."0.1.0" = {
    futures = "0.1.26";
  };
  deps.trust_dns_proto."0.5.0" = {
    byteorder = "1.3.1";
    failure = "0.1.5";
    futures = "0.1.26";
    idna = "0.1.5";
    lazy_static = "1.3.0";
    log = "0.4.6";
    rand = "0.5.6";
    smallvec = "0.6.9";
    socket2 = "0.3.8";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    tokio_tcp = "0.1.3";
    tokio_timer = "0.2.10";
    tokio_udp = "0.1.3";
    url = "1.7.2";
  };
  deps.trust_dns_proto."0.6.3" = {
    byteorder = "1.3.1";
    failure = "0.1.5";
    futures = "0.1.26";
    idna = "0.1.5";
    lazy_static = "1.3.0";
    log = "0.4.6";
    rand = "0.5.6";
    smallvec = "0.6.9";
    socket2 = "0.3.8";
    tokio_executor = "0.1.7";
    tokio_io = "0.1.12";
    tokio_reactor = "0.1.9";
    tokio_tcp = "0.1.3";
    tokio_timer = "0.2.10";
    tokio_udp = "0.1.3";
    url = "1.7.2";
  };
  deps.trust_dns_resolver."0.10.3" = {
    cfg_if = "0.1.7";
    failure = "0.1.5";
    futures = "0.1.26";
    lazy_static = "1.3.0";
    log = "0.4.6";
    lru_cache = "0.1.2";
    resolv_conf = "0.6.2";
    smallvec = "0.6.9";
    tokio = "0.1.19";
    trust_dns_proto = "0.6.3";
    ipconfig = "0.1.9";
  };
  deps.try_lock."0.2.2" = {};
  deps.try_from."0.3.2" = {
    cfg_if = "0.1.7";
  };
  deps.ucd_util."0.1.3" = {};
  deps.unicase."1.4.2" = {
    version_check = "0.1.5";
  };
  deps.unicase."2.4.0" = {
    version_check = "0.1.5";
  };
  deps.unicode_bidi."0.3.4" = {
    matches = "0.1.8";
  };
  deps.unicode_normalization."0.1.8" = {
    smallvec = "0.6.9";
  };
  deps.unicode_width."0.1.5" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.untrusted."0.6.2" = {};
  deps.url."1.7.2" = {
    encoding = "0.2.33";
    idna = "0.1.5";
    matches = "0.1.8";
    percent_encoding = "1.0.1";
  };
  deps.utf8_ranges."1.0.2" = {};
  deps.uuid."0.7.4" = {
    rand = "0.6.5";
  };
  deps.v_escape."0.7.2" = {
    v_escape_derive = "0.5.3";
    version_check = "0.1.5";
  };
  deps.v_escape_derive."0.5.3" = {
    nom = "4.2.3";
    proc_macro2 = "0.4.29";
    quote = "0.6.12";
    syn = "0.15.33";
  };
  deps.v_htmlescape."0.4.3" = {
    cfg_if = "0.1.7";
    v_escape = "0.7.2";
  };
  deps.vcpkg."0.2.6" = {};
  deps.vec_map."0.8.1" = {};
  deps.version_check."0.1.5" = {};
  deps.want."0.0.6" = {
    futures = "0.1.26";
    log = "0.4.6";
    try_lock = "0.2.2";
  };
  deps.which."1.0.5" = {
    libc = "0.2.54";
  };
  deps.widestring."0.2.2" = {};
  deps.winapi."0.2.8" = {};
  deps.winapi."0.3.7" = {
    winapi_i686_pc_windows_gnu = "0.4.0";
    winapi_x86_64_pc_windows_gnu = "0.4.0";
  };
  deps.winapi_build."0.1.1" = {};
  deps.winapi_i686_pc_windows_gnu."0.4.0" = {};
  deps.winapi_util."0.1.2" = {
    winapi = "0.3.7";
  };
  deps.winapi_x86_64_pc_windows_gnu."0.4.0" = {};
  deps.wincolor."1.0.1" = {
    winapi = "0.3.7";
    winapi_util = "0.1.2";
  };
  deps.winreg."0.5.1" = {
    winapi = "0.3.7";
  };
  deps.winutil."0.1.1" = {
    winapi = "0.3.7";
  };
  deps.ws2_32_sys."0.2.1" = {
    winapi = "0.2.8";
    winapi_build = "0.1.1";
  };
}
