name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v13
    - name: Setup cachix
      uses: cachix/cachix-action@v7
      with:
        name: local-nix-cache
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A pkg
